### ISSUE TITLE
CG solver for Smoke Plume examples

### ISSUE THREAD

**Issue by ayano721** [fluidnetsc22/fluidnet_sc22#3]
Hi @fluidnetsc22 
Thank you for  answer my question last time.
I have one more question for supporting for CG solver under [Plume_3D.py]

I want to apply and compare to CG solver to fluid-net results using Smoke Plume, but in that case, we have to make a summation of **RHS** for  pressure solver(divergence of the velocity field, "div **U** ") to **0.**
To satisfy this condition, I want to add the correct outlet velocity field(considering with inlet velocity field).
Is there an easy way or example with your code to make a summation of "div **U**"  to 0 by setting outlet velocity field ?

Many thanks in advance for any help or code you can provide!

**Comment by DABH** [comment]
(Moreover, what boundary conditions were you trying to set for your smoke plume example?  The Poisson system is incompatible when you have all Neumann boundary conditions but the net inflow and outflow don't match (discretely, when the right-hand side doesn't sum to zero).  It seems like FluidNet is still somehow producing some reasonable results, but I wonder if this is a bug in the example?  Maybe there should be outlet BCs that balance the inlet BCs, which is what @ayano721 is suggesting -- and maybe FluidNet would perform a bit better in that case?)

**Comment by fluidnetsc22** [comment]
Hi @ayano721 and @DABH. Thanks again for taking your time to thoroughly study this work!

Concerning the plume simulation, it is indeed one of the weaknesses of the developed solver. It is true that an outlet condition should help using the CG solver in such a case. However, I could not manage to correctly develop a pressure outlet condition, as I kept running into reverse flows (particularly due to the advection part, I believe).  Moreover, just forcing a velocity outlet condition (as done with the VK test case) did not yield great results, as the velocity outlet condition is not as trivial as for the VK test case.

However, even if the BC handling is not perfectly handled, the network prediction highlights particularly the importance of a symmetric prediction, mimicking the behavior of a Jacobi solver, dissipating the divergence sources. That is why the plume simulations are not compared to a reference CG solver, although the network behavior still yields some interesting conclusions. 

I reckon similar test cases such as a rising bubble (with no inflow condition) could also yield interesting results on buoyancy driven flows. 

Anyway, again, thank you very much for your helpful remarks.

**Comment by fluidnetsc22** [comment]
Hello, and sorry for the delay, a [script](https://github.com/fluidnetsc22/fluidnet_sc22/blob/main/pytorch/Bubble_3D.py) and [config file ](https://github.com/fluidnetsc22/fluidnet_sc22/blob/main/pytorch/config_files/inference/Bubble_3D/Config_Bubble_3D.yaml)to perform rising bubble simulations has just been added as well to perform rising bubble simulations, while open plume simulations still need some work. Anyway thanks in advance!

**Comment by ayano721** [comment]
Hi @fluidnetsc22
thank you too, for your advice and helpful replying.
I succeeded to run your test.
